### ISSUE TITLE
so im like really close i got 15% and 14%

### ISSUE THREAD

**Issue by NikCasar** [NikCasar/registration-form#2]
I think its cause the button isn't centered, ive tried doing everything i can think of. -nikki

@muxlowc
@ mackenzierose

**Comment by NikCasar** [comment]
ok so i got the button centered but still now both the screenshots are 14%

**Comment by muxlowc** [comment]
@NikCasar 

try centering your button like this:

```
    <div class="text-center">
      <button class="btn" type="submit">Register for the trip!</button>
    </div>
```
Also, make sure you add a border-bottom to your h1
